import 'package:pair/pair.dart';

List<Pair<String, String>> ancientGreece = [
  const Pair("776 BC: The first Olympic Games are held", 'The Olympic Games, a tradition that continues to this day, first took place in ancient Greece in 776 BC. These games were a religious and athletic festival held in Olympia in honor of Zeus. The games were held every four years, and participation was limited to freeborn Greek males. The ancient Olympic Games were abolished by the Roman emperor Theodosius I in 393 AD'),
  const Pair("750-550 BC: The Greek Colonisation of the Mediterranean", "greece_750-550BC.png"),
  const Pair("570 BC: Pythagoras is born on Samos", 'Pythagoras, born on the island of Samos in 570 BC, was a Greek philosopher and mathematician. He is best known for the Pythagorean theorem, which states that in a right-angled triangle, the square of the hypotenuse is equal to the sum of the squares of the other two sides. Pythagoras also made significant contributions to the fields of music and astronomy'),
  const Pair("499-479 BC: The Greco-Persian Wars", "499-479Greece-persianWar.jpg"),
  const Pair("431-404 BC: The Peloponnesian War", 'The Peloponnesian War, fought between 431 and 404 BC, was a devastating conflict between the two leading Greek city-states, Athens and Sparta. The war was marked by brutal battles, political intrigue, and widespread suffering. Sparta ultimately emerged victorious, but the war left Greece weakened and vulnerable to external threats'),
  const Pair("399 BC: Socrates is put on trial and executed", 'Socrates, an Athenian philosopher who lived from 470 to 399 BC, is considered one of the founders of Western philosophy. He is known for his Socratic method of questioning, which challenged traditional beliefs and encouraged critical thinking. Socrates was put on trial and executed in 399 BC on charges of impiety and corrupting the youth'),
  const Pair("387 BC: Plato founds the Academy in Athens", 'Plato, a student of Socrates, was another influential Athenian philosopher. He founded the Academy in Athens in 387 BC, an institution that would become a center of learning for centuries. Plato is best known for his theory of Forms, which posits that the physical world is a mere shadow of a higher realm of perfect and eternal Forms'),
  const Pair("334-326 BC: The Conquests of Alexander the Great", "334-326BCAlexander.jpg"),
  const Pair("323 BC: Alexander the Great dies at Babylon", 'Alexander the Great died in Babylon on June 10, 323 BC, at the age of 32. Malaria or Typhoid Fever: These were common in Babylon and align with the reported symptoms of his illness. Poisoning: Some historians have speculated about poisoning, but there no definitive evidence to support this.Alcoholic Liver Disease: Alexander was known to enjoy heavy drinking, which could have contributed to his demise.'),
  const Pair("287 BC: Archimedes is born in Syracuse", "Archimedes, born in Syracuse in 287 BC, was a Greek mathematician, physicist, engineer, inventor, and astronomer. He is considered one of the leading scientists in classical antiquity. Among his advances in physics are the foundations of hydrostatics, statics, and an explanation of the principle of the lever. He is credited with designing innovative machines"),
  const Pair("214-205 BC: The 1st Macedonian War", "214-205BCMacedonianWar.png"),
];

List<Uri> ancientGreeceUri = [
  Uri.parse('https://flutter.dev'),
  Uri.parse('https://en.wikipedia.org/wiki/Greek_colonisation'),
  Uri.parse('https://en.wikipedia.org/wiki/Pythagoras'),
  Uri.parse('https://en.wikipedia.org/wiki/Greco-Persian_Wars'),
  Uri.parse('https://en.wikipedia.org/wiki/Peloponnesian_War'),
  Uri.parse('https://en.wikipedia.org/wiki/Trial_of_Socrates'),
  Uri.parse('https://en.wikipedia.org/wiki/Platonic_Academy'),
  Uri.parse('https://en.wikipedia.org/wiki/Wars_of_Alexander_the_Great'),
  Uri.parse('https://en.wikipedia.org/wiki/Archimedes'),
  Uri.parse('https://en.wikipedia.org/wiki/First_Macedonian_War')
];

List<Pair<String, String>> ancientRome = [
  const Pair("753 BC: Legendary founding of Rome by Romulus", "According to Roman legend, Rome was founded in 753 BC by twin brothers Romulus and Remus, sons of the god Mars. Abandoned as infants, they were miraculously saved by a she-wolf and raised by a shepherd. Though the exact date and circumstances of Rome's founding are debated by historians, the legend of Romulus and Remus remains a powerful symbol of the city's origins."),
  const Pair("509 BC: Establishment of the Roman Republic", "The Roman Republic was established in 509 BC after the overthrow of the last Roman king, Tarquin the Proud. This marked a significant shift in Roman governance, replacing monarchy with a system based on elected officials, the Senate, and assemblies of citizens. The Republic era saw the expansion of Roman territory and the development of Roman law and political institutions."),
  const Pair("264-146 BC: Punic Wars against Carthage", "Map_of_Rome_and_Carthage.png"),
  const Pair("49 BC: Julius Caesar crosses the Rubicon", "Julius Caesar's crossing of the Rubicon River in 49 BC marked the beginning of the Roman Civil War. This decisive act defied the authority of the Roman Senate, leading to a power struggle that ultimately resulted in Caesar's victory and the rise of his dictatorship."),
  const Pair("44 BC: Assassination of Julius Caesar", "Julius Caesar, the renowned Roman general and statesman, was assassinated on the Ides of March (March 15), 44 BC, by a group of senators led by Brutus and Cassius. This event plunged Rome into further political turmoil and ultimately paved the way for the rise of the Roman Empire."),
  const Pair("27 BC: Augustus becomes the first Roman Emperor", "In 27 BC, Octavian, Caesar's adopted heir, was granted the title of Augustus by the Roman Senate, marking the beginning of the Roman Empire. Augustus ushered in an era of peace and prosperity known as the Pax Romana, which lasted for centuries."),
  const Pair("64 AD: Great Fire of Rome", "The Great Fire of Rome, a devastating fire that raged for several days in 64 AD, destroyed much of the city center. While the exact cause of the fire remains uncertain, it led to significant rebuilding efforts and the construction of new, more fire-resistant buildings under Emperor Nero's rule."),
  const Pair("313 AD: Edict of Milan legalizes Christianity", "The Edict of Milan, issued in 313 AD by Roman Emperors Constantine and Licinius, granted official tolerance to Christianity within the Roman Empire. This marked a turning point in the history of Christianity, allowing it to flourish and eventually become the dominant religion in the Roman Empire."),
  const Pair("395 AD: Division of the Roman Empire into East and West", "Division_of_rome_east_west.jpg"),
  const Pair("410 AD: Visigoths sack Rome", "In 410 AD, the Visigoths, a Germanic tribe, successfully sacked the city of Rome, a shocking event that symbolized the decline of Roman power and marked a turning point in the history of Western Europe."),
  const Pair("476 AD: Fall of the Western Roman Empire", "western_romw_fell.png")
];

List<Uri> ancientRomeUri = [
  Uri.parse("https://en.wikipedia.org/wiki/Foundation_of_Rome"),
  Uri.parse("https://en.wikipedia.org/wiki/Roman_Republic"),
  Uri.parse("https://en.wikipedia.org/wiki/Punic_Wars"),
  Uri.parse("https://en.wikipedia.org/wiki/Crossing_of_the_Rubicon"),
  Uri.parse("https://en.wikipedia.org/wiki/Assassination_of_Julius_Caesar"),
  Uri.parse("https://en.wikipedia.org/wiki/Augustus"),
  Uri.parse("https://en.wikipedia.org/wiki/Great_Fire_of_Rome"),
  Uri.parse("https://en.wikipedia.org/wiki/Edict_of_Milan"),
  Uri.parse("https://en.wikipedia.org/wiki/Division_of_the_Roman_Empire"),
  Uri.parse("https://en.wikipedia.org/wiki/Sack_of_Rome_(410)"),
  Uri.parse("https://en.wikipedia.org/wiki/Fall_of_the_Western_Roman_Empire"),
];

const List<Pair<String, String>> ancientEgypt = [
  Pair('c. 3150 BC: Unification of Upper and Lower Egypt', 
       "Around 3150 BC, Upper and Lower Egypt were united under the rule of King Narmer (or Menes), marking the beginning of the dynastic period in Egyptian history."),
  Pair('c. 2686 BC: Beginning of the Old Kingdom', 
       "The Old Kingdom (c. 2686-2181 BC) is considered the 'Golden Age' of the Egyptian civilization. It was a period of great prosperity and monumental construction, most notably the building of the Great Pyramids at Giza."),
  Pair('c. 2589-2504 BC: Reign of Khufu (Cheops), builder of the Great Pyramid of Giza', "Great_Pyramid_of_Giza_-_Pyramid_of_Khufu.jpg"),
  Pair('c. 2181-2055 BC: First Intermediate Period', 
       "The First Intermediate Period (c. 2181-2055 BC) was a time of political instability and social unrest following the decline of the Old Kingdom. Local rulers gained power, and the central government weakened."),
  Pair('c. 2055-1650 BC: Middle Kingdom', 
       "The Middle Kingdom (c. 2055-1650 BC) saw a resurgence of centralized power and a flourishing of Egyptian culture. This period is known for its impressive architecture, literature, and advancements in administration."),
  Pair('c. 1550-1069 BC: New Kingdom', 
       "The New Kingdom (c. 1550-1069 BC) was a period of Egyptian military expansion and cultural achievement. Powerful pharaohs like Ramses II and Hatshepsut led military campaigns and built magnificent temples and monuments."),
  Pair('c. 1279-1213 BC: Reign of Ramesses II, the Great', 'Ramses_II_British_Museum.jpg'),
  Pair('c. 1353-1336 BC: Reign of Akhenaten, the Heretic King', 
       "Akhenaten, a pharaoh of the 18th Dynasty, is known for his radical religious reforms. He attempted to replace the traditional polytheistic religion of Egypt with a monotheistic worship of the sun-disk, Aten."),
  Pair('c. 664 BC: Assyrian conquest of Egypt', 
       "In 664 BC, the Assyrian Empire conquered Egypt, marking the end of Egypt's independence for a period of time."),
  Pair('Reign of Tutankhamun', 'Reign_of_Tutankhamun.jpg'),
  Pair('332 BC: Conquest of Egypt by Alexander the Great', 
       "In 332 BC, Alexander the Great conquered Egypt, marking the end of Persian rule and the beginning of the Hellenistic period in Egypt."),
  Pair('30 BC: Egypt becomes a Roman province', 
       "In 30 BC, Egypt was annexed by Rome and became a Roman province, ending the Ptolemaic dynasty that had ruled Egypt since the death of Alexander the Great.")
];

List<Uri> ancientEgyptUri = [
  Uri.parse('https://en.wikipedia.org/wiki/Narmer_Palette'),
  Uri.parse('https://en.wikipedia.org/wiki/Old_Kingdom_of_Egypt'),
  Uri.parse('https://en.wikipedia.org/wiki/Khufu'),
  Uri.parse('https://en.wikipedia.org/wiki/First_Intermediate_Period'),
  Uri.parse('https://en.wikipedia.org/wiki/Middle_Kingdom_of_Egypt'),
  Uri.parse('https://en.wikipedia.org/wiki/New_Kingdom_of_Egypt'),
  Uri.parse('https://en.wikipedia.org/wiki/Ramesses_II'),
  Uri.parse('https://en.wikipedia.org/wiki/Akhenaten'),
  Uri.parse('https://en.wikipedia.org/wiki/Assyrian_conquest_of_Egypt'),
  Uri.parse('https://en.wikipedia.org/wiki/Tutankhamun'),
  Uri.parse('https://en.wikipedia.org/wiki/Conquest_of_Egypt_by_Alexander_the_Great'),
  Uri.parse('https://en.wikipedia.org/wiki/Roman_Egypt'),
];

const List<Pair<String, String>> ancientIndia = [
  Pair("305 BC: Chandragupta Maurya defeats Seleucus I Nicator", 
       "Chandragupta Maurya, a former general of the Nanda Empire, defeated Seleucus I Nicator, one of Alexander the Great's generals, in a series of battles. The peace treaty following the war included territorial concessions and the exchange of ambassadors, marking the beginning of diplomatic relations between India and the Hellenistic world."),
  Pair("300 BC: Establishment of the Mauryan Empire", 
       "The Mauryan Empire, founded by Chandragupta Maurya, unified a vast portion of the Indian subcontinent, stretching from Afghanistan in the west to Bengal in the east. This period witnessed significant advancements in administration, with the establishment of a centralized bureaucracy and efficient tax collection systems. The Mauryan Empire also saw a flourishing of agriculture, trade."),
  Pair("273-232 BC: Reign of Ashoka the Great", "ashoka_map.png"),
  Pair("261 BC: Kalinga War", 
       "The Kalinga War, a major battle fought between the Mauryan Empire under Ashoka and the independent kingdom of Kalinga, resulted in significant casualties. The brutality of the war deeply impacted Ashoka, leading him to renounce violence and embrace Buddhism. He subsequently adopted a policy of non-violence (dhamma) and actively promoted the spread of Buddhist principles throughout his empire."),
  Pair("c. 250 BC: Third Buddhist Council", 
       "The Third Buddhist Council, convened by Emperor Ashoka at Pataliputra, aimed to purify the Buddhist teachings and standardize the Buddhist canon. This council played a crucial role in preserving and disseminating Buddhist doctrines, contributing to the spread of Buddhism across Asia. The teachings were compiled and standardized, ensuring the continuity and purity of Buddhist principles for generations to come."),
  Pair("185 BC: Decline of the Mauryan Empire", 
       "The Mauryan Empire began to decline after the death of Ashoka. Internal rebellions, weakening of central authority, and external pressures from neighboring kingdoms contributed to its eventual collapse. The empire gradually fragmented, and regional powers began to assert their independence."),
  Pair("c. 100 BC: Rise of the Satavahana dynasty", 
       "The Satavahana dynasty emerged as a prominent power in southern India, playing a significant role in the cultural and economic development of the region. They patronized art, literature, and religion, and their rule witnessed the flourishing of trade and commerce."),
  Pair("78 CE: Shaka era begins", 
       "The Shaka era, a calendar era still used in India, commenced in 78 CE during the rule of the Kushan dynasty. This era marks the beginning of a new era in Indian history, coinciding with the rise of the Kushans, a powerful Central Asian dynasty that ruled over parts of North India."),
  Pair("c. 320 CE: Gupta Empire established", 
       "The Gupta Empire, often referred to as the 'Golden Age of India,' was established around 320 CE. This period witnessed significant advancements in various fields, including mathematics, astronomy, medicine, and literature. The Gupta period is renowned for the works of renowned scholars like Aryabhata (mathematics and astronomy) and Kalidasa (literature)."),
  Pair("c. 335-380 CE: Reign of Samudragupta", "Reign_of_Samudragupta.png"),
  Pair("c. 380-415 CE: Reign of Chandragupta II", 
       "Chandragupta II, also known as Vikramaditya, expanded the Gupta Empire to its greatest extent. He was a renowned patron of arts and literature, and his court was adorned by the 'Nine Jewels,' a group of celebrated scholars and poets."),
  Pair("c. 450 CE: Decline of the Gupta Empire", 
       "The Gupta Empire began to decline in the 5th century CE due to a combination of factors, including internal rebellions, weakening of central authority, and invasions by the Huns. These challenges led to the gradual disintegration of the empire and the rise of regional powers."),
  Pair("c. 4th-8th Century CE: Rise of regional kingdoms (Chalukyas, Pallavas, Cholas, Pandyas)", 
       "Following the decline of the Gupta Empire, several regional kingdoms emerged and flourished in different parts of India. The Chalukyas, Pallavas, Cholas, and Pandyas were among the most prominent, contributing significantly to Indian art, architecture, literature, and religious traditions."),
  Pair("c. 8th-12th Century CE: Chola dynasty reaches its zenith", 
       "The Chola dynasty, known for its powerful navy and extensive maritime trade, reached its zenith during this period. They built magnificent temples, such as the Brihadeeswarar Temple in Thanjavur, which stand as testaments to their architectural prowess and cultural achievements."),
  Pair("c. 1206 CE: Delhi Sultanate established by Qutub-ud-din Aibak", 
       "The Delhi Sultanate, established by Qutub-ud-din Aibak, a former slave general of the Ghurid dynasty, marked the beginning of Muslim rule in much of northern India. This period witnessed a significant exchange of cultural and intellectual ideas between India and the Islamic world, influencing Indian art, architecture, and literature."),
  Pair("c. 13th-14th Century CE: Rule of the Khilji and Tughlaq dynasties", 
       "The Khilji and Tughlaq dynasties ruled over the Delhi Sultanate, expanding its territory and implementing administrative reforms. However, this period also witnessed internal conflicts and challenges to their authority."),
  Pair("1398 CE: Invasion of Timur", 
       "The invasion of Timur (Tamerlane), a Central Asian conqueror, caused widespread destruction and devastation across northern India. This event significantly weakened the Delhi Sultanate and disrupted its political and economic stability."),
  Pair("c. 1526 CE: Mughal Empire founded by Babur", 
       "The Mughal Empire, founded by Babur, a descendant of Timur, ruled over much of India for over three centuries. This period witnessed a flourishing of art, architecture, and culture. The Mughals introduced Persian and Central Asian influences, enriching the cultural landscape of India."),
  Pair("1556-1605 CE: Reign of Akbar", "Mughal-Empire-during-Akbar-Period.jpg"),
  Pair("1605-1627 CE: Reign of Jahangir", 
       "Jahangir, known for his love of art and patronage of artists, continued the legacy of his father, Akbar. His reign saw the flourishing of miniature painting and other artistic forms."),
  Pair("1628-1658 CE: Reign of Shah Jahan", 
       "Shah Jahan is renowned for his architectural marvels, most notably the Taj Mahal, a magnificent mausoleum built in memory of his wife Mumtaz Mahal. His reign also witnessed significant advancements in architecture, literature, and music."),
  Pair("1658-1707 CE: Reign of Aurangzeb", "Reign_of_Aurangzeb.jpg"),
  Pair("1757: Battle of Plassey", 
       "The Battle of Plassey, fought between the Nawab of Bengal and the British East India Company, marked a turning point in Indian history. The British victory established their dominance in India and laid the foundation for British colonial rule."),
  Pair("1857: Indian Rebellion of 1857", 
       "The Indian Rebellion of 1857, also known as the Sepoy Mutiny, was a significant uprising against British rule. This rebellion had a profound impact on British policies in India, leading to significant changes in their governance and ultimately paving the way for greater Indian participation in administration."),
  Pair("1905: Partition of Bengal", 
       "The Partition of Bengal, a controversial administrative decision by the British, sparked widespread protests and fueled the Indian nationalist movement. This event united Indians against British rule and strengthened the movement for independence."),
  Pair("1919: Jallianwala Bagh massacre", 
       "The Jallianwala Bagh massacre, where British troops fired upon a peaceful gathering of Indians, was a pivotal event in the Indian independence movement. This horrific incident galvanized public opinion against British rule and intensified the demand for independence."),
  Pair("1920: Non-Cooperation Movement", 
       "The Non-Cooperation Movement, launched by Mahatma Gandhi, marked a significant step in the Indian struggle for independence. This movement emphasized non-violent resistance, civil disobedience, and boycott of British goods."),
  Pair("1930: Salt Satyagraha", 
       "The Salt Satyagraha, led by Gandhi, was a powerful act of civil disobedience that challenged the British salt tax. This movement mobilized millions of Indians and brought the injustices of British rule to the forefront of the global stage."),
  Pair("1942: Quit India Movement", 
       "The Quit India Movement, launched in 1942, called for the immediate and complete withdrawal of British rule from India. This movement intensified the struggle for independence")
];

List<Uri> ancientIndiaUri = [
  Uri.parse("https://en.wikipedia.org/wiki/Chandragupta_Maurya#Rise_to_power"),
  Uri.parse("https://en.wikipedia.org/wiki/Mauryan_Empire"),
  Uri.parse("https://en.wikipedia.org/wiki/Ashoka"),
  Uri.parse("https://en.wikipedia.org/wiki/Kalinga_War"),
  Uri.parse("https://en.wikipedia.org/wiki/Buddhist_councils"),
  Uri.parse("https://en.wikipedia.org/wiki/Mauryan_Empire#Decline_of_the_Mauryan_Empire"),
  Uri.parse("https://en.wikipedia.org/wiki/Satavahana_dynasty"),
  Uri.parse("https://en.wikipedia.org/wiki/Shaka_calendar"),
  Uri.parse("https://en.wikipedia.org/wiki/Gupta_Empire"),
  Uri.parse("https://en.wikipedia.org/wiki/Samudragupta"),
  Uri.parse("https://en.wikipedia.org/wiki/Chandragupta_II"),
  Uri.parse("https://en.wikipedia.org/wiki/Gupta_Empire#Decline_of_the_Gupta_Empire"),
  Uri.parse("https://en.wikipedia.org/wiki/Chalukya_dynasty"), 
  Uri.parse("https://en.wikipedia.org/wiki/Chola_dynasty"),
  Uri.parse("https://en.wikipedia.org/wiki/Delhi_Sultanate"),
  Uri.parse("https://en.wikipedia.org/wiki/Khilji_dynasty"), 
  Uri.parse("https://en.wikipedia.org/wiki/Timur_the_Lame#Indian_expedition"),
  Uri.parse("https://en.wikipedia.org/wiki/Mughal_Empire"),
  Uri.parse("https://en.wikipedia.org/wiki/Akbar"),
  Uri.parse("https://en.wikipedia.org/wiki/Jahangir"),
  Uri.parse("https://en.wikipedia.org/wiki/Shah_Jahan"),
  Uri.parse("https://en.wikipedia.org/wiki/Aurangzeb"),
  Uri.parse("https://en.wikipedia.org/wiki/Battle_of_Plassey"),
  Uri.parse("https://en.wikipedia.org/wiki/Indian_Rebellion_of_1857"),
  Uri.parse("https://en.wikipedia.org/wiki/Partition_of_Bengal"),
  Uri.parse("https://en.wikipedia.org/wiki/Jallianwala_Bagh_massacre"),
  Uri.parse("https://en.wikipedia.org/wiki/Non-Cooperation_Movement"),
  Uri.parse("https://en.wikipedia.org/wiki/Salt_March"),
  Uri.parse("https://en.wikipedia.org/wiki/Quit_India_Movement"),
  Uri.parse("https://en.wikipedia.org/wiki/Indian_independence_movement"),
  Uri.parse("https://en.wikipedia.org/wiki/Partition_of_India"),
  Uri.parse("https://en.wikipedia.org/wiki/Constitution_of_India")
];