import 'package:pair/pair.dart';

var ancientGreece = [
  const Pair<String, String?>("776 BC: The first Olympic Games are held", null),
  const Pair<String, String?>("750-550 BC: The Greek Colonisation of the Mediterranean", ""),
  const Pair<String, String?>("570 BC: Pythagoras is born on Samos", ""),
  const Pair<String, String?>("499-479 BC: The Greco-Persian Wars", ""),
  const Pair<String, String?>("431-404 BC: The Peloponnesian War", ""),
  const Pair<String, String?>("399 BC: Socrates is put on trial and executed", null),
  const Pair<String, String?>("387 BC: Plato founds the Academy in Athens", null),
  const Pair<String, String?>("776 BC: The first Olympic Games are held", null),
  const Pair<String, String?>("334-326 BC: The Conquests of Alexander the Great", ""),
  const Pair<String, String?>("323 BC: Alexander the Great dies at Babylon", null),
  const Pair<String, String?>("287 BC: Archimedes is born in Syracuse", null),
  const Pair<String, String?>("214-205 BC: The 1st Macedonian War", ""),
];

var ancientRome = [
  const Pair<String, String?>("753 BC: Legendary founding of Rome by Romulus", null),
  const Pair<String, String?>("509 BC: Establishment of the Roman Republic", null),
  const Pair<String, String?>("264-146 BC: Punic Wars against Carthage", ""),
  const Pair<String, String?>("49 BC: Julius Caesar crosses the Rubicon", null),
  const Pair<String, String?>("44 BC: Assassination of Julius Caesar", null),
  const Pair<String, String?>("27 BC: Augustus becomes the first Roman Emperor", null),
  const Pair<String, String?>("64 AD: Great Fire of Rome", null),
  const Pair<String, String?>("313 AD: Edict of Milan legalizes Christianity", null),
  const Pair<String, String?>("395 AD: Division of the Roman Empire into East and West", ""),
  const Pair<String, String?>("410 AD: Visigoths sack Rome", null),
  const Pair<String, String?>("476 AD: Fall of the Western Roman Empire", "")
];

const List<Pair<String, String?>> ancientEgypt = [
  Pair('c. 3150 BC: Unification of Upper and Lower Egypt', null),
  Pair('c. 2686 BC: Beginning of the Old Kingdom', null),
  Pair('c. 2589-2504 BC: Reign of Khufu (Cheops), builder of the Great Pyramid of Giza', ""),
  Pair('c. 2181-2055 BC: First Intermediate Period', ""),
  Pair('c. 2055-1650 BC: Middle Kingdom', ""),
  Pair('c. 1550-1069 BC: New Kingdom', ""),
  Pair('c. 1353-1336 BC: Reign of Akhenaten, the Heretic King', ''),
  Pair('c. 1323-1306 BC: Reign of Tutankhamun', ""),
  Pair('c. 1279-1213 BC: Reign of Ramesses II, the Great', ''),
  Pair('c. 664 BC: Assyrian conquest of Egypt', null),
  Pair('332 BC: Conquest of Egypt by Alexander the Great', null),
  Pair('30 BC: Egypt becomes a Roman province', null),
];

const List<Pair<String, String?>> ancientIndia = [
  Pair("305 BC: Chandragupta Maurya defeats Seleucus I Nicator", null),
  Pair("300 BC: Establishment of the Mauryan Empire", null),
  Pair("273-232 BC: Reign of Ashoka the Great", ""),
  Pair("261 BC: Kalinga War", null),
  Pair("c. 250 BC: Third Buddhist Council", null),
  Pair("185 BC: Decline of the Mauryan Empire", null),
  Pair("c. 100 BC: Rise of the Satavahana dynasty", null),
  Pair("78 CE: Shaka era begins", null),
  Pair("c. 320 CE: Gupta Empire established", null),
  Pair("c. 335-380 CE: Reign of Samudragupta", ""),
  Pair("c. 380-415 CE: Reign of Chandragupta II", ""),
  Pair("c. 450 CE: Decline of the Gupta Empire", null),
  Pair("c. 4th-8th Century CE: Rise of regional kingdoms (Chalukyas, Pallavas, Cholas, Pandyas)", ""),
  Pair("c. 8th-12th Century CE: Chola dynasty reaches its zenith", ""),
  Pair("c. 1206 CE: Delhi Sultanate established by Qutub-ud-din Aibak", null),
  Pair("c. 13th-14th Century CE: Rule of the Khilji and Tughlaq dynasties", ""),
  Pair("1398 CE: Invasion of Timur", null),
  Pair("c. 1526 CE: Mughal Empire founded by Babur", null),
  Pair("1556-1605 CE: Reign of Akbar", ""),
  Pair("1605-1627 CE: Reign of Jahangir", ""),
  Pair("1628-1658 CE: Reign of Shah Jahan", ""),
  Pair("1658-1707 CE: Reign of Aurangzeb", ""),
  Pair("1757: Battle of Plassey", null),
  Pair("1857: Indian Rebellion of 1857", null),
  Pair("1905: Partition of Bengal", null),
  Pair("1919: Jallianwala Bagh massacre", null),
  Pair("1920: Non-Cooperation Movement", null),
  Pair("1930: Salt Satyagraha", null),
  Pair("1942: Quit India Movement", null),
  Pair("1947: Indian Independence", null),
  Pair("1947: Partition of India", null),
  Pair("1950: Constitution of India adopted", null),
];